name: nook_configurator
version: 0.0.1

environment:
  sdk: ^2.7.0

dependencies:
  firebase: ^7.2.0
  http: ^0.12.0
  intl: ^0.16.0
  chartjs:
    git: https://github.com/marianamarasoiu/chartjs.dart.git

dev_dependencies:
  build_runner: ^1.7.0
  build_web_compilers: ^2.9.0
